### ISSUE TITLE
java.lang.NoSuchMethodError when Generating new account

### ISSUE THREAD

**Issue by SynnWy** [nemtech/nem2-sdk-java#10]
I have java.lang.NoSuchMethodError when i try to generate new account with keypair.

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Hex.decodeHex(Ljava/lang/String;)[B
	at io.nem.sdk.model.account.Address.generateEncoded(Address.java:114)
	at io.nem.sdk.model.account.Address.createFromPublicKey(Address.java:107)
	at io.nem.sdk.model.account.PublicAccount.<init>(PublicAccount.java:33)
	at io.nem.sdk.model.account.Account.<init>(Account.java:44)
	at com.emis.fund.base.service.AccountService.generateAccK(AccountService.java:68)
	at com.emis.fund.base.controller.AccountController.GenerateAccount(AccountController.java:21)
	at com.emis.fund.base.controller.WalletController.GenerateWalletModelPRNG(WalletController.java:41)
	at main.main(main.java:58)

**Comment by gigonzalezs** [comment]
There is a dependency problem with Apache commons codec.

Add this dependency to your project in order to override the default release:

<dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.11</version>
</dependency>

**Comment by fboucquez** [comment]
New SDK (master) depends on commons-codec 1.11. Closing this issue. Please let me know if you have more dependencies problems.
