### ISSUE TITLE
Cannot deserialize instance of `io.nem.sdk.infrastructure.UInt64DTO<java.lang.Long>` out of VALUE_STRING token

### ISSUE THREAD

**Issue by ernestochero** [nemtech/nem2-sdk-java#126]
Hi team,
I'm trying nem2 and catapult for the first time in Scala, but when I try to get the account information of an address, an exception appears.
``` import io.nem.sdk.infrastructure.AccountHttp
import io.nem.sdk.model.account.Address
object App {
  def main(args: Array[String]): Unit = {
    val accountHttp = new AccountHttp("http://localhost:3000")
    val address =
      Address.createFromRawAddress("SAJPSBGA7CWXUMGWIS2JSY6MDG5U26BY4RL65QTS")
    val accountInfo = accountHttp.getAccountInfo(address)
    accountInfo.subscribe(in => println(s"information : ${in}"))
  }
}
```
The exception is the following:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
io.reactivex.exceptions.OnErrorNotImplementedException: Cannot deserialize instance of `io.nem.sdk.infrastructure.UInt64DTO<java.lang.Long>` out of VALUE_STRING token
 at [Source: (String)"{"account":{"address":"9012F904C0F8AD7A30D644B49963CC19BB4D7838E457EEC272","addressHeight":"1","publicKey":"6CB91498EAC62E53C0A417A3AD183A99C7CA07387345A69BEF01007A1BFA01FB","publicKeyHeight":"2","accountType":0,"linkedAccountKey":"0000000000000000000000000000000000000000000000000000000000000000","activityBuckets":[{"startHeight":"975","totalFeesPaid":"0","beneficiaryCount":37,"rawScore":"4312500"},{"startHeight":"936","totalFeesPaid":"0","beneficiaryCount":39,"rawScore":"4312500"},{"startHeight"[truncated 572 chars]; line: 1, column: 92] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["addressHeight"])
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `io.nem.sdk.infrastructure.UInt64DTO<java.lang.Long>` out of VALUE_STRING token
 at [Source: (String)"{"account":{"address":"9012F904C0F8AD7A30D644B49963CC19BB4D7838E457EEC272","addressHeight":"1","publicKey":"6CB91498EAC62E53C0A417A3AD183A99C7CA07387345A69BEF01007A1BFA01FB","publicKeyHeight":"2","accountType":0,"linkedAccountKey":"0000000000000000000000000000000000000000000000000000000000000000","activityBuckets":[{"startHeight":"975","totalFeesPaid":"0","beneficiaryCount":37,"rawScore":"4312500"},{"startHeight":"936","totalFeesPaid":"0","beneficiaryCount":39,"rawScore":"4312500"},{"startHeight"[truncated 572 chars]; line: 1, column: 92] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["addressHeight"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.nem.sdk.infrastructure.AccountHttp.lambda$getAccountInfo$0(AccountHttp.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	... 12 more
Exception in thread "vert.x-eventloop-thread-0" io.reactivex.exceptions.OnErrorNotImplementedException: Cannot deserialize instance of `io.nem.sdk.infrastructure.UInt64DTO<java.lang.Long>` out of VALUE_STRING token
 at [Source: (String)"{"account":{"address":"9012F904C0F8AD7A30D644B49963CC19BB4D7838E457EEC272","addressHeight":"1","publicKey":"6CB91498EAC62E53C0A417A3AD183A99C7CA07387345A69BEF01007A1BFA01FB","publicKeyHeight":"2","accountType":0,"linkedAccountKey":"0000000000000000000000000000000000000000000000000000000000000000","activityBuckets":[{"startHeight":"975","totalFeesPaid":"0","beneficiaryCount":37,"rawScore":"4312500"},{"startHeight":"936","totalFeesPaid":"0","beneficiaryCount":39,"rawScore":"4312500"},{"startHeight"[truncated 572 chars]; line: 1, column: 92] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["addressHeight"])
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `io.nem.sdk.infrastructure.UInt64DTO<java.lang.Long>` out of VALUE_STRING token
 at [Source: (String)"{"account":{"address":"9012F904C0F8AD7A30D644B49963CC19BB4D7838E457EEC272","addressHeight":"1","publicKey":"6CB91498EAC62E53C0A417A3AD183A99C7CA07387345A69BEF01007A1BFA01FB","publicKeyHeight":"2","accountType":0,"linkedAccountKey":"0000000000000000000000000000000000000000000000000000000000000000","activityBuckets":[{"startHeight":"975","totalFeesPaid":"0","beneficiaryCount":37,"rawScore":"4312500"},{"startHeight":"936","totalFeesPaid":"0","beneficiaryCount":39,"rawScore":"4312500"},{"startHeight"[truncated 572 chars]; line: 1, column: 92] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["addressHeight"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.nem.sdk.infrastructure.AccountHttp.lambda$getAccountInfo$0(AccountHttp.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	... 12 more
```
3. Versions:
io.nem:sdk:0.9.1
nem2-cli v0.13.1
latest Catapult Service Bootstrap

Thanks in advance.

**Comment by fboucquez** [comment]
Hi @ernestochero ,

Thank you for contacting us.

We are working on the new version of nem2-sdk-java that we are going to release soon. At the moment you can use the snapshot version by including 

Maven:

```xml
<dependency>
    <groupId>io.nem</groupId>
    <artifactId>sdk-vertx-client</artifactId>
    <version>0.13.0</version>
</dependency>
```
Gradle: 
```compile 'io.nem:sdk-vertx-client:0.13.0-SNAPSHOT```

Please include the snapshot repositories to your Gradle or maven config.

https://oss.sonatype.org/content/repositories/snapshots.

Please follow the release notes, we will announce when a new release version is in Maven central, you can then remove the SNAPSHOT version and repository.

**Comment by ernestochero** [comment]
Hi @fboucquez 
I'm using SBT to load libraryDependencies , there is a way to work with this snapshot using sbt.
Thanks

**Comment by fboucquez** [comment]
Hi @ernestochero, 

I haven't used SBT myself but I'm sure you can add a repo and include the snapshot dependency. 

Maybe this can help?

https://stackoverflow.com/questions/8224907/re-download-a-snapshot-version-of-a-dependency-using-sbt

We are targeting to have a release version in the next few days.

**Comment by ernestochero** [comment]
Hi @fboucquez, I solved my problem by adding this line to my build.sbt : 
```resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"```
and then import the library 
`libraryDependencies += "io.nem" % "sdk-vertx-client" % "0.13.0-SNAPSHOT" changing()` 
Thanks for your help, I will be waiting for the new release version. 
Please close this issue.

**Comment by fboucquez** [comment]
Perfect. Thanks!
