### ISSUE TITLE
Http call exception does not contain the actual error stack.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-sdk-java#192]
1. Expected behavior and actual behavior.
When there is a failure in the deserialization of an object from rest, the exception stack does not show where the actual error happened.  The exception stack is always as below.  It would nice to have for debug-ability.

    public RepositoryCallException exceptionHandling(Throwable e,
        IllegalArgumentException originalException) {
        if (e instanceof RepositoryCallException) {
            return (RepositoryCallException) e;
        }
        return new RepositoryCallException(
            extractMessageFromException(e),
            extractStatusCodeFromException(e), originalException);
    }

Caused by: io.nem.sdk.api.RepositoryCallException: DecoderException: exception decoding Hex string: null
	at io.nem.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.exceptionHandling(AbstractRepositoryVertxImpl.java:66) ~[sdk-vertx-client-0.16.0.jar:?]
	at io.nem.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.lambda$onError$0(AbstractRepositoryVertxImpl.java:95) ~[sdk-vertx-client-0.16.0.jar:?]
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59) ~[rxjava-2.1.7.jar:?]
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41) ~[vertx-rx-java2-3.5.0.jar:?]
	at io.nem.sdk.openapi.vertx.invoker.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:570) ~[api-vertx-client-0.7.21.jar:?]
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125) ~[vertx-web-client-3.5.0.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) ~[vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]

**Comment by fboucquez** [comment]
Fixed in https://github.com/nemtech/nem2-sdk-java/pull/202
