### ISSUE TITLE
Deserialization Error on Mosaic checks on an account

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-sdk-java#3]
Similar to the [jackson issue](https://github.com/nemtech/nem2-sdk-java/issues/2), there is another error while checking the mosaics... 

Step - 1 Get the test account and test tokens
Step - 2 Create a namespace: testspace
Step - 3 Create Mosaic: testingmosaic
Step - 4 List the owned Mosaics

Code:
```java
  Account account = Account.createFromPrivateKey("created primary key", NetworkType.MIJIN_TEST);
        AccountHttp accountHttp = new AccountHttp("http://localhost:3000");
        MosaicHttp mosaicHttp = new MosaicHttp("http://localhost:3000");

       /**
       	Namesapce creation
       	Mosaic Creation
       */


        accountHttp.getAccountInfo(account.getAddress()).subscribe(accountInfo -> {
           accountInfo
                   .getMosaics()
                   .stream()
                   .map(mosaic ->  mosaic.getId())
                   .forEach(mosaicId -> {
                        mosaicHttp
                                .getMosaicNames(Collections.singletonList(mosaicId))
                                .subscribe(mosaicNames -> {
                                    mosaicNames.forEach(mosaicName -> {
                                        System.out.println(mosaicName.getName());
                                    });
                                });
                   });
        });
```
Output:
```
xem

io.reactivex.exceptions.OnErrorNotImplementedException: Failed to decode: Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: (String)"{"code":"InvalidArgument","message":"element in array mosaicIds has an invalid format"}"; line: 1, column: 1]
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableToList$ToListObserver.onError(ObservableToList.java:93)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onError(ObservableFlattenIterable.java:125)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:65)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.vertx.reactivex.ext.web.client.HttpRequest$6.handle(HttpRequest.java:409)
	at io.vertx.reactivex.ext.web.client.HttpRequest$6.handle(HttpRequest.java:404)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: io.vertx.core.json.DecodeException: Failed to decode: Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: (String)"{"code":"InvalidArgument","message":"element in array mosaicIds has an invalid format"}"; line: 1, column: 1]
	at io.vertx.core.json.Json.decodeValue(Json.java:124)
	at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:659)
	at io.vertx.core.json.JsonArray.<init>(JsonArray.java:51)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl.lambda$static$2(BodyCodecImpl.java:39)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl$1.end(BodyCodecImpl.java:101)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$4(HttpContext.java:144)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:261)
	at io.vertx.core.http.impl.ClientConnection.handleResponseEnd(ClientConnection.java:358)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:100)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:36)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	... 2 more
Exception in thread "vert.x-eventloop-thread-1" io.reactivex.exceptions.OnErrorNotImplementedException: Failed to decode: Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: (String)"{"code":"InvalidArgument","message":"element in array mosaicIds has an invalid format"}"; line: 1, column: 1]
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableToList$ToListObserver.onError(ObservableToList.java:93)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onError(ObservableFlattenIterable.java:125)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:65)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.vertx.reactivex.ext.web.client.HttpRequest$6.handle(HttpRequest.java:409)
	at io.vertx.reactivex.ext.web.client.HttpRequest$6.handle(HttpRequest.java:404)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: io.vertx.core.json.DecodeException: Failed to decode: Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: (String)"{"code":"InvalidArgument","message":"element in array mosaicIds has an invalid format"}"; line: 1, column: 1]
	at io.vertx.core.json.Json.decodeValue(Json.java:124)
	at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:659)
	at io.vertx.core.json.JsonArray.<init>(JsonArray.java:51)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl.lambda$static$2(BodyCodecImpl.java:39)
	at io.vertx.ext.web.codec.impl.BodyCodecImpl$1.end(BodyCodecImpl.java:101)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$4(HttpContext.java:144)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:261)
	at io.vertx.core.http.impl.ClientConnection.handleResponseEnd(ClientConnection.java:358)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:100)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:36)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	... 2 more
```

while below code works fine, for verifying/checking the created mosaic:
```java
mosaicHttp.getMosaicsFromNamespace(new NamespaceId("testspace")).subscribe(mosaicInfos ->{
            mosaicInfos.forEach(mosaicInfo -> {
                System.out.println("mosaic id from namespace -> " + mosaicInfo.getMosaicId().getId() );
            });
        });



        accountHttp.getAccountInfo(account.getAddress()).subscribe(accountInfo -> {
            accountInfo.getMosaics().forEach(mosaic -> {
                System.out.println("mosaic id from account -> " + mosaic.getId().getId() );
            });
        });
```
Output:
    mosaic id from account -> -3087871471161192663
    mosaic id from account -> -173929953159242042
    mosaic id from namespace -> -173929953159242042

For the code which creates the above stacktrace, adding onError in the subscribe in streams makes it disappear, but still only "xem" is printed at the end, while there is another mosaic in the account.

**Comment by Suheil123** [comment]
Which version of Catapult SDK are you using? I ran the same code above in version 0.9.1 and no error or exception was displayed. The end result was as desired. All my Mosaics were displayed
![image](https://user-images.githubusercontent.com/32008573/51225460-aa4c9080-1985-11e9-8e51-6b803c1364ec.png)
