### ISSUE TITLE
java.lang.NoClassDefFoundError when generate new account

### ISSUE THREAD

**Issue by razvi97** [nemtech/nem2-sdk-java#45]
I have this error every time I want to create new account. I'm working with Android.

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: io.nem.core.crypto.-$$Lambda$WpUAPn_432WlX_5COiSC4C3Fcbw
        at io.nem.core.crypto.Hashes.hash(Hashes.java:68)
        at io.nem.core.crypto.Hashes.sha3_512(Hashes.java:53)
        at io.nem.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:38)
        at io.nem.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:50)
        at io.nem.core.crypto.KeyPair.<init>(KeyPair.java:52)
        at io.nem.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:45)
        at io.nem.core.crypto.KeyPair.<init>(KeyPair.java:29)

**Comment by fullcircle23** [comment]
Hi @razvi97. Thanks for reporting the issue. Please provide complete details of the method you are using to create the new account. Thank you.

**Comment by fboucquez** [comment]
Hi @razvi97, we have released a new version 0.14.0 with many changes. Can you replicate the problem in the new version?

**Comment by fboucquez** [comment]
Hi @razvi97 

I'm closing this issue. If you have any other problem please report it.

Cheers
Fernando
