### ISSUE TITLE
Unclear Response on Namespace Check (v. 0.9.0)

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-sdk-java#6]
Following https://nemtech.github.io/guides/namespace/registering-a-namespace.html

I have tried to create a namespace called "mytwentyfive", then run the below code:

```java
NamespaceHttp namespaceHttp = new NamespaceHttp(CATAPULT_API_ENDPOINT);


        final NamespaceId namespaceId = new NamespaceId("maytwentyfive");


        namespaceHttp.getNamespace(namespaceId).subscribe(
                namespaceInfo -> {
                    System.out.println(namespaceInfo);
                },
                error -> {
                    error.printStackTrace();
                });
```

Then the stack trace I am seeing is

```text
java.lang.RuntimeException: Conflict
	at io.nem.sdk.infrastructure.Http.mapJsonObjectOrError(Http.java:67)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

and on https://github.com/nemtech/nem2-sdk-java/blob/master/src/main/java/io/nem/sdk/infrastructure/Http.java#L67 I assume it is an HTTP 409 response, but no further details. 
Would it be better if there are some further details in such responses to make the situation clearer? And what exactly "Conflict" error mean for the case above?

**Comment by denizdurmus** [comment]
Sth similar is happening for mosaics as well
