### ISSUE TITLE
Missing field accountType in io.nem.sdk.infrastructure.AccountDTO

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#81]
Hi team, 

I'm trying nem2 and catapult for the first time. I'm following up the [getting started](https://nemtech.github.io/getting-started/first-application.html) page using the Java SDK to test the BC server. 

I've found that the io.nem.sdk.infrastructure.AccountDTO misses the field accountType.It seems like the Jackson 2 java DTO model is not up to date with the rest API.

2. Steps:

Create an account
Run the following test
```java
package nem2.sdk.java.test;

import io.nem.sdk.infrastructure.AccountHttp;
import io.nem.sdk.model.account.AccountInfo;
import io.nem.sdk.model.account.Address;
import org.junit.Assert;
import org.junit.Test;

import java.net.MalformedURLException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class NemSdkIntegrationTests {

    @Test
    public void getAccountInfo() throws MalformedURLException, InterruptedException, ExecutionException {
        ExecutorService executorService = Executors.newCachedThreadPool();
        CompletableFuture<AccountInfo> future = new CompletableFuture<>();
        AccountHttp accountHttp = new AccountHttp("http://localhost:3000");
        String address = "YOUR ACCOUNT ID";
        executorService.submit(() -> {
            Address addressObject = Address.createFromRawAddress(address);
            accountHttp.getAccountInfo(addressObject).subscribe(future::complete, future::completeExceptionally);
        });

        AccountInfo accountInfo = future.get();
        Assert.assertEquals(address, accountInfo.getAddress().plain());

    }
}
```

The exception is the following:

```
java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "accountType" (class io.nem.sdk.infrastructure.AccountDTO), not marked as ignorable (7 known properties: "address", "publicKey", "mosaics", "addressHeight", "publicKeyHeight", "importance", "importanceHeight"])
 at [Source: (String)"{"meta":{},"account":{"address":"9088E5AC330AAF89DAB4A56E5E0FEEFD3A8CC4AA23617D97AD","addressHeight":[1,0],"publicKey":"16CF30A830E133F640183BBDCB59522AAECD8651293D817376DA9662EAC557A8","publicKeyHeight":[316,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[],"mosaics":[{"id":[2774703640,78176032],"amount":[136036448,104762]},{"id":[3150471759,468215766],"amount":[1000000,0]}],"importance":[0,0],"importanceHeight":[0,0]}}"; line: 1, column: 228] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["accountType"])

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at nem2.sdk.java.test.NemSdkIntegrationTests.getAccountInfo(NemSdkIntegrationTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "accountType" (class io.nem.sdk.infrastructure.AccountDTO), not marked as ignorable (7 known properties: "address", "publicKey", "mosaics", "addressHeight", "publicKeyHeight", "importance", "importanceHeight"])
 at [Source: (String)"{"meta":{},"account":{"address":"9088E5AC330AAF89DAB4A56E5E0FEEFD3A8CC4AA23617D97AD","addressHeight":[1,0],"publicKey":"16CF30A830E133F640183BBDCB59522AAECD8651293D817376DA9662EAC557A8","publicKeyHeight":[316,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[],"mosaics":[{"id":[2774703640,78176032],"amount":[136036448,104762]},{"id":[3150471759,468215766],"amount":[1000000,0]}],"importance":[0,0],"importanceHeight":[0,0]}}"; line: 1, column: 228] (through reference chain: io.nem.sdk.infrastructure.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.AccountDTO["accountType"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at io.nem.sdk.infrastructure.AccountHttp.lambda$getAccountInfo$0(AccountHttp.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

3. Versions:

- io.nem:sdk:0.9.0 (the latest code io.nem:sdk:0.9.1 doesn't have the field either)
- nem2-cli v0.13.0
- latest Catapult Service Bootstrap (master trunk)

**Comment by fboucquez** [comment]
One recommendation: I reckon you should configure you Jackson 2 object mapper or annotate the generated entity with "ignore unknown properties"

https://www.baeldung.com/jackson-deserialize-json-unknown-properties

Ignoring unknown properties will allow better backward compatibility between a new server and an old java client especially when adding new attributes to the API objects (like an account in this case)

**Comment by fboucquez** [comment]
Note, FAIL_ON_UNKNOWN_PROPERTIES has been set to false in the latest code. 

This issue would be to just add accountType the Account information.

**Comment by dgarcia360** [comment]
Hi @fboucquez,

Thanks for reporting the issue! It seems that the latest versions of catapult-rest return new additional properties that were not documented. I have opened this PR to amend the Open API spec to be java compatible (https://github.com/nemtech/nem2-docs/pull/229).

If you detect any other inconsistency, do not hesitate to comment on the PR. We have a pending in-depth revision of the open API spec in the near future.

**Comment by fboucquez** [comment]
PR to be created from branch

https://github.com/fboucquez/nem2-sdk-java/tree/task/81_missing_account_type
