### ISSUE TITLE
 com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2611055438) out of range of int

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-sdk-java#83]
I'm trying to load my default account info using the Java SDK and I get the following error:

```
java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2611055438) out of range of int
 at [Source: (String)"{"meta":{},"account":{"address":"901508D3519B6CC0936A04233073D3D903E1DFBEF95DC204AB","addressHeight":[1,0],"publicKey":"089E931203F63EECF695DB94957B03E1A6B7941532069B687386D6D4A7B6BE4A","publicKeyHeight":[21,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[{"startHeight":"1404","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"1365","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"13"[truncated 778 chars]; line: 1, column: 937]
 at [Source: (String)"{"meta":{},"account":{"address":"901508D3519B6CC0936A04233073D3D903E1DFBEF95DC204AB","addressHeight":[1,0],"publicKey":"089E931203F63EECF695DB94957B03E1A6B7941532069B687386D6D4A7B6BE4A","publicKeyHeight":[21,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[{"startHeight":"1404","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"1365","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"13"[truncated 778 chars]; line: 1, column: 927] (through reference chain: io.nem.sdk.infrastructure.model.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.model.AccountDTO["mosaics"]->java.util.ArrayList[0]->io.nem.sdk.infrastructure.model.MosaicDTO["id"]->java.util.ArrayList[0])

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at nem2.sdk.java.test.NemSdkIntegrationTests.getAccountInfo(NemSdkIntegrationTests.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2611055438) out of range of int
 at [Source: (String)"{"meta":{},"account":{"address":"901508D3519B6CC0936A04233073D3D903E1DFBEF95DC204AB","addressHeight":[1,0],"publicKey":"089E931203F63EECF695DB94957B03E1A6B7941532069B687386D6D4A7B6BE4A","publicKeyHeight":[21,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[{"startHeight":"1404","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"1365","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"13"[truncated 778 chars]; line: 1, column: 937]
 at [Source: (String)"{"meta":{},"account":{"address":"901508D3519B6CC0936A04233073D3D903E1DFBEF95DC204AB","addressHeight":[1,0],"publicKey":"089E931203F63EECF695DB94957B03E1A6B7941532069B687386D6D4A7B6BE4A","publicKeyHeight":[21,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[{"startHeight":"1404","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"1365","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"13"[truncated 778 chars]; line: 1, column: 927] (through reference chain: io.nem.sdk.infrastructure.model.AccountInfoDTO["account"]->io.nem.sdk.infrastructure.model.AccountDTO["mosaics"]->java.util.ArrayList[0]->io.nem.sdk.infrastructure.model.MosaicDTO["id"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at io.nem.sdk.infrastructure.AccountHttp.lambda$getAccountInfo$0(AccountHttp.java:69)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2611055438) out of range of int
 at [Source: (String)"{"meta":{},"account":{"address":"901508D3519B6CC0936A04233073D3D903E1DFBEF95DC204AB","addressHeight":[1,0],"publicKey":"089E931203F63EECF695DB94957B03E1A6B7941532069B687386D6D4A7B6BE4A","publicKeyHeight":[21,0],"accountType":0,"linkedAccountKey":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","activityBuckets":[{"startHeight":"1404","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"1365","totalFeesPaid":"0","beneficiaryCount":0,"rawScore":"3750000"},{"startHeight":"13"[truncated 778 chars]; line: 1, column: 937]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:867)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:799)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	... 30 more
```
2611055438 is greater than max int 2147483647

![image](https://user-images.githubusercontent.com/5390558/61984686-c3558e80-b005-11e9-825e-62bc889b9520.png)

I think the ulong ids represented with UInt64DTO in the DTOs are being converted from a list of long to a list of int somewhere in the serialization process causing this error.

2. The test is the following
```
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nem2.sdk.java.test;

import io.nem.sdk.infrastructure.AccountHttp;
import io.nem.sdk.model.account.AccountInfo;
import io.nem.sdk.model.account.Address;
import java.net.MalformedURLException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.junit.Assert;
import org.junit.Test;

public class NemSdkIntegrationTests {

    @Test
    public void getAccountInfo()
        throws MalformedURLException, InterruptedException, ExecutionException {
        ExecutorService executorService = Executors.newCachedThreadPool();
        CompletableFuture<AccountInfo> future = new CompletableFuture<>();
        AccountHttp accountHttp = new AccountHttp("http://localhost:3000");
        String address = "SAKQRU-2RTNWM-BE3KAQ-RTA46T-3EB6DX-567FO4-EBFL";
        executorService.submit(() -> {
            Address addressObject = Address.createFromRawAddress(address);
            Assert.assertEquals("SAKQRU2RTNWMBE3KAQRTA46T3EB6DX567FO4EBFL", addressObject.plain());
            accountHttp.getAccountInfo(addressObject)
                .subscribe(future::complete, future::completeExceptionally);
        });

        AccountInfo accountInfo = future.get();
        Assert.assertEquals(address, accountInfo.getAddress().plain());

    }
}

```

To replicate you would need to generate enough ids (for example creating or transferring mosaics) until one of the ids is higher than the int limit.

3. Version: latest nem2-java-sdk jar build from the master (0.13.0)

**Comment by fboucquez** [comment]
The generated MosaicDTOs use a list of integer instead of a list of long.

![image](https://user-images.githubusercontent.com/5390558/61985231-935bba80-b008-11e9-8151-eb39f5e59902.png)

I reckon the DO generator needs to be changed so it generates lists of longs for example. DTO to model mappers need to be changed so they handle lists of longs.

A question I have: why does the generated DTOs use Google's GSON annotations when the SDK uses Jackson 2 parse JSON objects? Is the SDK using both JSON libs?

**Comment by fboucquez** [comment]
Hi @dgarcia360,

The main problem is that the intent of the openapi3 descriptor is to use uint for the UInt64DTO type. There is no uint in java and the generator is generating an array of int (so the out of range when a generated id is higher than 2147483647)

2 options:
1) Change the openapi3 descriptor for a type different than int32 (int64) (yaml change, @dgarcia360)
2) Change the openAPI3 tool configuration to generate arrays of longs (generator change,@fboucquez )

What do you think?

Cheers

Fernando

**Comment by dgarcia360** [comment]
Thanks for raising the issue. I think that we could change int32 for int64 to allow the correct representation in typed languages. Please, open an issue or create a PR if you find more inconsistencies with other fields.

@rg911 Do you know if this would have a negative effect on nem2-sdk-typescript?

Off-topic: We are planning to deprecate the UInt64DTO in a future open API spec version. This DTO does not let us document the individual properties using it, and there is no way right now between a MosaicId, NamespaceId or BlockDuration being represented with a DTO. Do you have any recommendation?

**Comment by fboucquez** [comment]
@rg911 , @fullcircle23 this is fixed in master. 

The trick is done in ``io.nem.sdk.model.transaction.UInt64.fromLongArray``. The method takes just 4 bytes from the long numbers corresponding to the uint part.

Close this issue if you think it's fixed
