### ISSUE TITLE
 Jackson Binding Exception while checking for chain info 

### ISSUE THREAD

**Issue by denizdurmus** [nemtech/nem2-sdk-java#9]
Similar to the issue #2 (which mentions about the chain info part there as well)

```java
blockchainHttp.getBlockchainHeight().subscribe((height) ->{
            blockchainHttp.getBlockByHeight(height).subscribe((blockinfo) ->{
                System.out.println(blockinfo.getHash());
            },
                    err ->{
                        System.out.println(err);
                    });
        },
                err ->{
                    System.out.println(err);
                });
```

The output for the above code is:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "merkleTree" (class io.nem.sdk.infrastructure.BlockMetaDTO), not marked as ignorable (4 known properties: "totalFee", "numTransactions", "hash", "generationHash"])
 at [Source: (String)"{"meta":{"hash":"34C48B64E78E4DCF8BC1238E17EE56AC71C3897361F259CCFF4706FFFAC78DCE","generationHash":"2F59A2AACC6E8D746A7F62E39B1F1EE4627AAB93EA3E9E6B0809A85325AE81D2","totalFee":[0,0],"numTransactions":0,"merkleTree":["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="]},"block":{"signature":"9666B2012A01BFC52E6C49ABB2AD3DB1E4880BA8F363FE39F6CCE34B976351436A3D1AFA815205314A9403B4302BCA1F237EC387754927338F6013DBCC366A0E","signer":"95865F9B544B0A28691F9960CEE0CEBC65B0C74A8B17735F6060049C98DB359D","vers"[truncated 282 chars]; line: 1, column: 219] (through reference chain: io.nem.sdk.infrastructure.BlockInfoDTO["meta"]->io.nem.sdk.infrastructure.BlockMetaDTO["merkleTree"])
```

And for 
```java

blockchainHttp.getBlockByHeight(blockchainHttp.getBlockchainHeight().blockingFirst()).blockingFirst();
```

The more verbose version:

```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "merkleTree" (class io.nem.sdk.infrastructure.BlockMetaDTO), not marked as ignorable (4 known properties: "totalFee", "numTransactions", "hash", "generationHash"])
 at [Source: (String)"{"meta":{"hash":"5E1ED944CAE5169CB3E79B96CB0DF4306FC6FD4AC436612054A6D8D05057ADFA","generationHash":"1FB1B5CB8080DDCFB3BB8CB32878FBD64A648C265831704E64038BF130560629","totalFee":[0,0],"numTransactions":0,"merkleTree":["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="]},"block":{"signature":"D9204EDA309A3A3D7DA2569FD6C140ECB4D03727F38CD6AB0DE5A16E3632384A756B9C096F30C0F60C92711E371E6E22DC5B40719940D2DDDEED6F128C4D0B0F","signer":"95865F9B544B0A28691F9960CEE0CEBC65B0C74A8B17735F6060049C98DB359D","vers"[truncated 282 chars]; line: 1, column: 219] (through reference chain: io.nem.sdk.infrastructure.BlockInfoDTO["meta"]->io.nem.sdk.infrastructure.BlockMetaDTO["merkleTree"])
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingBaseObserver.blockingGet(BlockingBaseObserver.java:80)
	at io.reactivex.Observable.blockingFirst(Observable.java:4845)
	at com.thenetcircle.cryptoplayground.App.main(App.java:688)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "merkleTree" (class io.nem.sdk.infrastructure.BlockMetaDTO), not marked as ignorable (4 known properties: "totalFee", "numTransactions", "hash", "generationHash"])
 at [Source: (String)"{"meta":{"hash":"5E1ED944CAE5169CB3E79B96CB0DF4306FC6FD4AC436612054A6D8D05057ADFA","generationHash":"1FB1B5CB8080DDCFB3BB8CB32878FBD64A648C265831704E64038BF130560629","totalFee":[0,0],"numTransactions":0,"merkleTree":["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="]},"block":{"signature":"D9204EDA309A3A3D7DA2569FD6C140ECB4D03727F38CD6AB0DE5A16E3632384A756B9C096F30C0F60C92711E371E6E22DC5B40719940D2DDDEED6F128C4D0B0F","signer":"95865F9B544B0A28691F9960CEE0CEBC65B0C74A8B17735F6060049C98DB359D","vers"[truncated 282 chars]; line: 1, column: 219] (through reference chain: io.nem.sdk.infrastructure.BlockInfoDTO["meta"]->io.nem.sdk.infrastructure.BlockMetaDTO["merkleTree"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at io.nem.sdk.infrastructure.BlockchainHttp.lambda$null$0(BlockchainHttp.java:61)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:469)
	at io.vertx.reactivex.ext.web.client.HttpRequest$8.handle(HttpRequest.java:466)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by aleixmorgadas** [comment]
Just published version 0.9.1 which should solve this issue just ignoring unknown properties, it's not the desired behaviour since we would like to add the latest features that the nem2-sdk-typescript has to nem2-sdk-java :sweat_smile: 

It should take a while to be available into maven repository, when so, and the issue it's solved, please, close the issue.
